marksull/fmcapi

- fmcapi/__init__.py
- fmcapi/fmc.py
File logging shouldn't be enabled by default in this package. Every time this package is loaded an output file is created so you end up with output files sprinkled all over the place. Anyone can setup their own default logger if they specifically need one for their application prior to calling FMC:
```
file = logging.FileHandler(filename="output.log")
file.setLevel(level=logging.DEBUG)
logger = logging.getLogger()
logger.addHandler(file)
with FMC(...
```
> Remove file logger enabled by default

- fmcapi/api_objects.py
Need to be able to create network objects with literals only without needing to create, bind, delete an object to a network object first
> Remove 'objects' from network object post requirements

- fmcapi/api_objects.py
I put a message in under "issues" a while back about this little change I needed. I was looking to automate adding a NetworkGroup to an already defined NetworkGroup object and couldn't see a way to do it, so I made this addition to your very handy fmcapi package.
Hopefully the change makes sense and I've used git (not done commits/pushing code in years) correctly to let you review it.
Thanks
> allow addition of NetworGroups to NetworkGroup objects

- fmcapi/api_objects/policy_services/accesspolicies.py
Put and Delete of Access Policy is definitely allowed in FMC. Checked release notes back to 6.1.0 and all subsequent releases have this capability. I've Monkey Patched this feature into our own code so though it time we get it into the offical code ;-)
> Remove feature suppression

- fmcapi/api_objects/policy_services/prefilterrules.py
When performing get() on prefilterrules objects the url has an extra '?' parameter separator because it is already added before the URL_SUFFIX parameter is set. This change matches other object classes (ie. AccessRules) and removes the extra '?' before returning the url.
> Changed URL_SUFFIX property return value

- fmcapi/api_objects/apiclasstemplate.py
- fmcapi/api_objects/policy_services/accessrules.py
I'm not certain about the logging.debug part, feel free to correct me on that...
- Add an action for "addgroup" to source_port and destination_port
- Move `json.dumps` to logging.debug
This maintains backwards compatibility by not changing the "add" action.
> Include addgroup function for source_port and destination_port. Debug json dumps.

- fmcapi/api_objects/policy_services/accessrules.py
Hello,
While configuring the applications in access rule policy there are two options 1) applications and 2) applicationfilters.
I added separate options for application ( add/remove/clear) and for applicationfilters ( addappfilter/removeappfilter/clear) under accessrules.py. Not sure if you want to include both options to have the support to add applicationfilters while configuring the access rules.
Thanks
> accessrules - application support

- fmcapi/api_objects/device_services/bridgegroupinterfaces.py
> Update bridgegroupinterfaces.py MTU range

- fmcapi/api_objects/device_services/etherchannelinterfaces.py
> Update etherchannelinterfaces.py MTU range

- fmcapi/api_objects/device_services/redundantinterfaces.py
> Update redundantinterfaces.py MTU range

- fmcapi/api_objects/device_services/subinterfaces.py
> Update subinterfaces.py MTU range

- fmcapi/api_objects/device_services/physicalinterfaces.py
> Update physicalinterfaces.py MTU range

- fmcapi/fmc.py
Rather than returning None, this will return the API response object when a call to the FMC fails. 
This will other code layered on this package to provide dynamic feedback in failure scenarios
> store json object as fmc class attribute when call to fmc api fails with http exception

- fmcapi/fmc.py
- requirements.txt
From [DateTime (not inbuilt `datetime`) homepage](https://pypi.org/project/DateTime)
> This package provides a DateTime data type, as known from Zope. Unless you need to communicate with Zope APIs, you're probably better off using Python's built-in datetime module.
`fmcapi` doesn't seem to use Zope types anywhere and `DateTime`'s dependency on `zope` is not pure Python. This is a blocker in certain use cases e.g. while using with [WASM python](https://github.com/pyodide/pyodide).
> Consider removing external datetime dependency

- fmcapi/api_objects/policy_services/autonatrules.py
You can specify description field for every nat rule. I tested this on fmc 6.7, but the field is there on older versions too.
> Support for description field in nat rule

- fmcapi/api_objects/policy_services/manualnatrules.py
Support for object groups was missing in the code. Only normal network objects could have been used. 
This was tested under FMC 6.7
> Support for network object groups in manual NAT rules

- fmcapi/api_objects/policy_services/manualnatrules.py
You can specify description field for every nat rule. I tested this on fmc 6.7, but the field is there on older versions too.
> Support for description field in nat rules

- fmcapi/api_objects/policy_services/accessrules.py
have tested with FMC 6.6.1, and characters "<", ">", "," are accepted.
example: 
'acp_rule_name': 'SA,HX and DL UCS OOB -> DNS'
> update name character validation

- fmcapi/api_objects/policy_services/accessrules.py
In addition to port objects and port groups, I've included support for ICMPv4 object in ACP rules. 
For now I needed only ICMPv4, but for other protocols (ICMPv6, IKE, etc) can be probably added in the same way.
> added support for ICMP objects

- fmcapi/api_objects/policy_services/accessrules.py
**New:**
- method for bulk deleting many access rules in one bulk request.  List of rules is derived from existing bulk class.
**Example:**
```
acpId = "<some guid>"
accessRule1 = AccessRules(fmc=fmc, acp_id=acpId)
accessRule2 = AccessRules(fmc=fmc, acp_id=acpId)
bulkPost = Bulk(fmc=fmc,url=(accessRule1.URL + "?")) 
bulkPost.add(accessRule1.show_json)
bulkPost.add(accessRule2.show_json)
bulkPost.delete()
```
**Note:**
Bulk class needs more work as explained in last post [of this issue](https://github.com/marksull/fmcapi/issues/63) . This change is just adding new method for bulk deleting.
> Bulk delete for access rules

- fmcapi/api_objects/policy_services/autonatrules.py
- fmcapi/api_objects/policy_services/manualnatrules.py
Keys in the dictionary should be referenced with [""]  , not with 'dot' notation. 
I was not able to pass options to the patPool. These changes were tested on python 3.10.12
> Dalamanster patch nat pool

- .gitignore
- TestingUserScript.py
- fmcapi/api_objects/__init__.py
- fmcapi/api_objects/apiclasstemplate.py
- fmcapi/api_objects/object_services/__init__.py
- fmcapi/api_objects/object_services/anyprotocolportobjects.py
- fmcapi/api_objects/object_services/fqdns.py
- fmcapi/api_objects/object_services/hosts.py
- fmcapi/api_objects/object_services/icmpv4objects.py
- fmcapi/api_objects/object_services/icmpv6objects.py
- fmcapi/api_objects/object_services/networkaddresses.py
- fmcapi/api_objects/object_services/networkgroups.py
- fmcapi/api_objects/object_services/networks.py
- fmcapi/api_objects/object_services/portobjectgroups.py
- fmcapi/api_objects/object_services/ports.py
- fmcapi/api_objects/object_services/protocolportobjects.py
- fmcapi/api_objects/object_services/ranges.py
- fmcapi/api_objects/object_services/urlgroups.py
- fmcapi/api_objects/object_services/urls.py
- fmcapi/api_objects/object_services/usage.py
- fmcapi/api_objects/object_services/vlangrouptags.py
- fmcapi/api_objects/object_services/vlantags.py
- unit_tests/__init__.py
- unit_tests/objects_get_query_filters.py
- unit_tests/usage.py
This satisfies #159. 
I am not super thrilled with how I am currently handling the get query filters. Mainly it does not reuse `REQUIRED_FOR_GET` and creates some confusion between kwargs and self variables. I've looked through the OAS spec more and Cisco's query filters seem very arbitrary and tend to mix (cause confusion) with preexisting self variable names. 
Example: 
`/object/operational/usage` filter `uuid` is just referenced everywhere else as `id`
> Support for find usage endpoint

- fmcapi/api_objects/__init__.py
- fmcapi/api_objects/health/__init__.py
- fmcapi/api_objects/health/terminateravpnsessions.py
- unit_tests/__init__.py
- unit_tests/terminateravpnsessions.py
This adds support for terminating RA VPN sessions. The documentation for this api endpoint is pretty broken and there is no get method. This has been reported to Cisco, but currently, I got this working with some trial and error.
> Support for terminatingravpnsessions

- fmcapi/fmc.py
[Cloud Delivered Firewall Management Centers (cdFMC)](https://www.cisco.com/c/en/us/td/docs/security/cdo/ftd-services-cdfmc-release-notes/cloud-delivered-firewall-management-center-release-notes/about-cloud-delivered-firewall-management-center.html) require use of API tokens to use the FMC REST API.  This pull request introduces support for usage of an `api_key` and `uuid` in the `FMC` object.
For now, if you're using an `api_key`, you must provide the `uuid` manually while creating the FMC object.  This domain `uuid` is pulled from the access token when using username/password with on-prem FMCs.
[cdFMC REST API info](https://www.cisco.com/c/en/us/td/docs/security/firepower/720/api/CDO_REST/cloud_delivered_firewall_management_center_rest_api_quick_start_guide_720/Connecting_With_A_Client.h …
> add api_key support

- TestingUserScript.py
- fmcapi/api_objects/__init__.py
- fmcapi/api_objects/device_services/devicerecords.py
- fmcapi/api_objects/object_services/__init__.py
- fmcapi/api_objects/object_services/grouppolicies.py
- fmcapi/api_objects/policy_services/__init__.py
- fmcapi/api_objects/policy_services/connectionprofiles.py
- fmcapi/api_objects/policy_services/dynamicaccesspolicies.py
- fmcapi/api_objects/policy_services/ravpns.py
- requirements.txt
- unit_tests/__init__.py
- unit_tests/connectionprofiles.py
- unit_tests/devicerecords.py
- unit_tests/dynamicaccesspolicies.py
- unit_tests/grouppolicies.py
- unit_tests/ravpn.py
Added support for:
RAVPN Policies
Group Policies
Connection Profiles
Will add the other child RAVPN policies as my need for them arise. Soon™
Devicerecords updated to work with most of the >7.2 get_filters.
> Support for RAVPN Policies and a couple of its child policies. Devicerecords getfilter

- setup.py
I believe this is needed in order for pip to know that xmltodict is required on a new pip install. #183 
If that is not the case let me know so I know for the future.
> add xmltodict to setup.py

- fmcapi/api_objects/deployment_services/deploymentrequests.py
- fmcapi/api_objects/update_packages/upgradepackage.py
- unit_tests/upgrades.py
- unit_tests/wait_for_task.py
updated upgradepackage to include the ability to trigger readiness checks and other newer flags in that api endpoint (based on fmc 7.4.1.1)
upgrade unit_test workflow now has an example of end to end ftd upgrade (push file, readiness check, upgrade, post upgrade deployment)
`fmcapi/api_objects/deployment_services/deploymentrequests.py` was modified and may break some code in the wild with this modification. 
Instead of returning just the device list in the deployment response, it made more sense to me to return the entire response and then pull the device list out outside of the object code. This also means that deploymentrequest now works and fits better with the existing `wait_for_task` unit_test
> updated upgradepackage and unit_test workflow as an example of end to end ftd upgrade

- fmcapi/api_objects/deployment_services/deploymentrequests.py
- unit_tests/deployment_requests.py
Added the ability to provide a list of devices to deployment requests so that you are not forced to deploy all devices at once if you don't want to. 
Deployment options: Force and IgnoreWarnings are now configurable as well
This implementation still defaults to deploying all devices with force and ignore warnings as to not break existing library code references or existing user written code.
> Selective Device Deployments

- fmcapi/api_objects/device_services/devicerecords.py
Notably, metadata was included as a possible kwarg upon finding out that deployment api and upgrade api utilize different device names if a device is in HA or a cluster. Metadata from device records allows you to search the device name and derive if a device is in HA/Cluster and derive that HA/Cluster name. This HA/Cluster name is what is used in deployment request. 
These were based on an FMC running 7.6
> Adding several missing possible kwargs for expanded device records

- fmcapi/api_objects/policy_services/loggingsettings.py
Method `parse_kwargs` is called before & after the FMC API call. The response for the PUT operation for syslogging doesn't contain ACP ID or ACP Name, resulting in the execution logs showing an error despite no actual error. 
Make this a warning instead of error.
> Use warning instead of error in loggingsettings

- fmcapi/api_objects/system_information/serverversion.py
This is a fix for #211 
It implements a safe get method for the geoVersion key to keep compatibility with FMC version <7.7 while allowing operations with FMC 7.7+ where this key is removed
> fix for issue#211

- fmcapi/api_objects/__init__.py
- fmcapi/api_objects/health/__init__.py
- fmcapi/api_objects/health/tunneldetails.py
- fmcapi/api_objects/health/tunnelstatuses.py
- fmcapi/api_objects/health/tunnelsummaries.py
- unit_tests/__init__.py
- unit_tests/tunneldetails.py
- unit_tests/tunnelstatuses.py
- unit_tests/tunnelsummaries.py
Added support for s2s tunnel health endpoints
> Added support for s2s tunnel health endpoints
